Deploy
awctw/study-dash pull request #43
Opened 2023-07-19 01:02 UTC by awctw

2023-07-19 23:43 UTC, HeinzUBC requested changes

2023-07-19 23:43 UTC, HeinzUBC commented on client/src/store/TODOList/services.js
> +      `${API_URL}/api/TODOList/${categoryID}`
This is wrong. It should be `${API_URL}/api/categories/${categoryID}`

2023-07-19 23:43 UTC, HeinzUBC commented on client/src/store/TODOList/services.js
> +    const response = await axios.get(`${API_URL}/api/TODOList/${userID}`);
This is wrong. It should be ${API_URL}/api/categories/${userID}

2023-07-20 18:33 UTC, HeinzUBC approved these changes

2023-07-20 23:23 UTC, kush458 approved these changes

2023-07-21 00:44 UTC, AlanZhangDev approved these changes
Works on my end for habits.

Just a note: I had an account set up already before recent changes, so the account in the DB did not have a first/last name field. As a result, there was a fatal error after login. However, I don't think it is possible to create a new user without a fast/last name field anymore, so this would only perhaps matter as a note for in the future, if new fields are added to users during production.

2023-07-21 04:32 UTC, leungkenneth approved these changes

2023-07-21 17:22 UTC, merged